# Generated by Django 4.2.4 on 2023-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('availability_status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('plant_care_guide', models.TextField()),
                ('special_facts', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('BZ', 'Bonzai'), ('PH', 'Plants for home'), ('PO', 'Plants for office'), ('GP', 'Gift Plants'), ('EP', 'Exotic Plants'), ('AC', 'Accessories')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
